# CMake generated Testfile for 
# Source directory: /home/ai8111/recovery/GOMC
# Build directory: /home/ai8111/recovery/GOMC/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BasicTypesTest_NVT "/home/ai8111/recovery/GOMC/build_test/GOMC_NVT_Test" "--gtest_filter=BasicTypesTest.*")
set_tests_properties(BasicTypesTest_NVT PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;30;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;42;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;64;add_NVT_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(MolLookupTest_NVT "/home/ai8111/recovery/GOMC/build_test/GOMC_NVT_Test" "--gtest_filter=CheckConsensusBeta.*")
set_tests_properties(MolLookupTest_NVT PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;32;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;42;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;64;add_NVT_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(BasicTypesTest_NPT "/home/ai8111/recovery/GOMC/build_test/GOMC_NPT_Test" "--gtest_filter=BasicTypesTest.*")
set_tests_properties(BasicTypesTest_NPT PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;30;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;46;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;65;add_NPT_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(MolLookupTest_NPT "/home/ai8111/recovery/GOMC/build_test/GOMC_NPT_Test" "--gtest_filter=CheckConsensusBeta.*")
set_tests_properties(MolLookupTest_NPT PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;32;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;46;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;65;add_NPT_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(BasicTypesTest_GCMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GCMC_Test" "--gtest_filter=BasicTypesTest.*")
set_tests_properties(BasicTypesTest_GCMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;30;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;50;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;66;add_GCMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(MolLookupTest_GCMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GCMC_Test" "--gtest_filter=CheckConsensusBeta.*")
set_tests_properties(MolLookupTest_GCMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;32;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;50;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;66;add_GCMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(ConsistentTrajectoryTest_GCMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GCMC_Test" "--gtest_filter=CheckPDBTrajCoordinates.*")
set_tests_properties(ConsistentTrajectoryTest_GCMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;36;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;50;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;66;add_GCMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(BasicTypesTest_GEMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GEMC_Test" "--gtest_filter=BasicTypesTest.*")
set_tests_properties(BasicTypesTest_GEMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;30;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;54;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;67;add_GEMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(MolLookupTest_GEMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GEMC_Test" "--gtest_filter=CheckConsensusBeta.*")
set_tests_properties(MolLookupTest_GEMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;32;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;54;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;67;add_GEMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
add_test(ConsistentTrajectoryTest_GEMC "/home/ai8111/recovery/GOMC/build_test/GOMC_GEMC_Test" "--gtest_filter=CheckPDBTrajCoordinates.*")
set_tests_properties(ConsistentTrajectoryTest_GEMC PROPERTIES  _BACKTRACE_TRIPLES "/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;36;add_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;54;add_ensemble_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;67;add_GEMC_test;/home/ai8111/recovery/GOMC/test/BuildCPUTests.cmake;0;;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;35;include;/home/ai8111/recovery/GOMC/test/GoogleTest.cmake;0;;/home/ai8111/recovery/GOMC/CMakeLists.txt;137;include;/home/ai8111/recovery/GOMC/CMakeLists.txt;0;")
subdirs("googletest-build")
